table Customer
	lineageTag: 27b84599-18e7-430c-85f3-bd9ff1920637
	sourceLineageTag: [dbo].[Customer]

	measure 'No of Customers with Sales' = CALCULATE(COUNTROWS(Customer), Sales)
		formatString: 0
		lineageTag: c1223b9e-7ebc-4f1d-ba2f-cb229241003e

		changedProperty = Name

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 13050f25-af72-41ee-a481-802ca30d8489
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e21dea66-4760-4959-b6ac-662f9b4833bb
		sourceLineageTag: Customer
		summarizeBy: none
		sourceColumn: Customer

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: aaa97c25-4779-4e1a-a3d4-b1e15b8d5b45
		sourceLineageTag: Category
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Buying Group'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7d1c980f-415f-4fe9-b230-7284e90eafb3
		sourceLineageTag: BuyingGroup
		summarizeBy: none
		sourceColumn: BuyingGroup

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6da4fbfe-c602-4560-b4fb-35b435f895c2
		sourceLineageTag: PostalCode
		summarizeBy: none
		sourceColumn: PostalCode

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

	partition Customer = entity
		mode: directLake
		source
			entityName: Customer
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

