table Info
	lineageTag: 608d5537-5160-469e-92f0-468bb265e3dd
	sourceLineageTag: [dbo].[Info]

	measure Environment = LOOKUPVALUE(Info[value], Info[key], "Environment")
		lineageTag: cfa8dd1b-2706-4172-81fd-04c0024ebe3d

		changedProperty = Name

	measure Version = LOOKUPVALUE(Info[value], Info[key], "Version")
		lineageTag: 9559c911-ef0e-4494-b12c-dee827246d46

		changedProperty = Name

	measure Pipeline = LOOKUPVALUE(Info[value], Info[key], "Pipeline")
		lineageTag: 8e688c2f-133e-46d8-a568-d4bbd0aa3ac1

		changedProperty = Name

	column key
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 212553a7-75ec-4031-9592-c58f2980649e
		sourceLineageTag: key
		summarizeBy: none
		sourceColumn: key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		isHidden
		sourceProviderType: varchar(8000)
		lineageTag: 321477f9-af0b-46b2-84ed-dccd47eecd4f
		sourceLineageTag: value
		summarizeBy: none
		sourceColumn: value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Info = entity
		mode: directLake
		source
			entityName: Info
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

